
name: DevOps Lab CI

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v4

    - name: 2. Build Docker image
      run: docker build -t log-monitor .

    - name: 3. Run container
      run: docker run log-monitor > output.txt

    - name: 4. Show logs (debug用)
      run: cat output.txt

    - name: 5. Check real ERROR only
      run: |
        if grep "ERROR" output.txt | grep -v "test"; then
          echo "❌ Real ERROR found"
          exit 1
        else
          echo "✅ Only test logs or no error"
        fi
