
name: DevOps Lab CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v4

    - name: 2. Build Docker image
      run: docker build -t log-monitor .

    - name: 3. Run container and capture output
      run: |
        docker run log-monitor > output.txt
        cat output.txt

    - name: 4. Check ERROR
      run: |
        if grep "ERROR" output.txt; then
          echo "❌ Found ERROR"
          exit 1
        else
          echo "✅ No ERROR"
        fi
