
name: CI - Docker Log Monitor

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t log-monitor .

      - name: Run container
        run: |
          docker run --name test-container log-monitor > output.txt 2>&1

      - name: Show output
        run: cat output.txt
